### ISSUE TITLE
Exclusive fullscreen mode incorrect resolution

### ISSUE THREAD

**Issue by startas** [AustinBorger/DXWindow#1]
When entering real fullscreen mode via F4 or F11 in your example program(using dx11 mode), it sets wrong resolution, I have noticed it because vsync wasn't working, and then I saw in console "new backbuffer : 1280x768", but my primary resolution is 1366x768, it happens on both intel hd 4400 and GeForce 840m, win10 x64.

**Comment by AustinBorger** [comment]
Ah I had no idea people were actually looking at this.

It's good that you're coming to me because I have no way of knowing if the code correctly chooses resolutions on other desktops.  On my desktop and laptop it seemed to work, and I was basically just crossing my fingers that the approach was correct.

You use visual studio, correct?  Is there some sort of a debug warning in visual studio's console?

What is your desktop resolution set to?  It's 1366x768, right?

**Comment by startas** [comment]
Yes, I'm using visual studio 2015 enterprise + windows 10 sdk. My desktop resolution is set to native - 1366x768. I was looking for a way to handle fullscreen / windowed modes in D3D11, and yours is the only one that actually works, even Microsoft themselves in samples just disables fullscreen mode / switching between modes, because they made it so much harder than it had to be. I'm not at home right now, so I will look for warnings later this evening, but I don't remember seeing any unusual warnings.

**Comment by AustinBorger** [comment]
Oh you're definitely right about it being harder than it needs to be.  There is only one possible combination of function calls that works even when it would seem like other combinations would work.  That took... a while to figure out.

I'm reviewing my code and there's a few places where the problem could be.  If you see that warning, that narrows it down to pretty much one place (`SwapChainController::ToggleFullscreen()`), and it means that - surprise surprise - the order in which I called the DXGI methods is wrong.

I'm going to go in and add a few more console outputs, and that should make it a lot easier to find what part of the code is causing the issue.

**Comment by AustinBorger** [comment]
Alright I added a bunch of relevant console outputs.  It's getting late and I have to go to sleep - there should be enough information in the console now for you to spot something strange.  Once you do, get back to me and I'll try and make the change.

Note that I've changed the console to appear only in debug mode.

**Comment by startas** [comment]
Hi, i tried your new version, and didn't really noticed anything except back buffer being created in wrong size:

DXWindowCreateWindow():
        Direct3D 11 Device detected.  Using DirectX 11.
Output::Initialize():
        AttachedToDesktop: true
        DesktopCoordinates.left: 0
        DesktopCoordinates.right: 1366
        DesktopCoordinates.top: 0
        DesktopCoordinates.bottom: 768
        DesktopCoordinates - width: 1366
        DesktopCoordinates - height: 768
        DeviceName: \.\DISPLAY1
        Monitor: 0x00010001
        Rotation: DXGI_MODE_ROTATION_IDENTITY
Output::GetWindowCenter():
        width (including border): 1296
        height (including border): 759
        xPos: 35
        yPos: -22
SwapChainController::CreateSwapChain():
        Buffer Width: 1280
        Buffer Height: 720
OnBackBufferCreate():
        Back Buffer Width: 1280
        Back Buffer Height: 720

<--Pressed F4 for fullscreen mode-->

OnBackBufferRelease()
SwapChainController::ToggleFullscreen():
        Currently Fullscreen? false
Output::GetDesktopArea():
        width: 1366
        height: 768
SwapChainController::ResizeBuffers()
SwapChainController::ResizeBuffers()
SwapChainController::ToggleFullscreen():
        Successfully set exclusive fullscreen state to TRUE.
SwapChainController::ResizeBuffers()
OnBackBufferCreate():
        Back Buffer Width: 1280
        Back Buffer Height: 768

<--Pressed F1 to go back to windowed mode-->

OnBackBufferRelease()
SwapChainController::ToggleFullscreen():
        Currently Fullscreen? true
SwapChainController::ResizeBuffers()
SwapChainController::ToggleFullscreen():
        Successfully set exclusive fullscreen state to FALSE.
Output::GetWindowCenter():
        width (including border): 1296
        height (including border): 759
        xPos: 35
        yPos: -22
SwapChainController::ResizeBuffers()
OnBackBufferCreate():
        Back Buffer Width: 1280
        Back Buffer Height: 720

And the only build warning i get is "DXWindowTest\PixelShader.hlsl(19,8-131): warning X3206: implicit truncation of vector type", which leads to the animation being half cut out on intel graphics, like the waves are waving from 1 to 0 and then resets, they do not go from 1 to -1 smooth. I mean, after entering fullscreen, i can manually set its size, but i'm interested in what is wrong with your code, or maybe its microsofts fault and their directx code is bugged.

**Comment by AustinBorger** [comment]
That's really bizarre, because I am directly supplying the desktop width and height to `ResizeTarget()` before entering fullscreen.  I added one more console output, mode.Width and mode.Height.  If they're 1366x768, it's possible I'm calling the DXGI APIs in the "wrong" order.

I also added an additional call to `ResizeTarget()` after calling `SetFullscreenState()`.  That didn't seem to harm anything on my end, maybe it will help you on your end.

**Comment by startas** [comment]
I'm looking now at what is happening exactly in the code, and when I press F4 to enter full screen, what happens is :

OnBackBufferRelease is called:
1) BackBufTex.Release(...);
2) BackBufRTV.Release(...);

m_SwapChainController.ToggleFullscreen() is called:
3) m_SwapChain->ResizeTarget (...);
4) m_SwapChain->SetFullscreenState (...);
5) m_SwapChain->ResizeTarget (...); // That's the new one
6) m_SwapChain->ResizeBuffers (...);

OnBackBufferCreate is called:
7) Device->CreateRenderTargetView (...);

OnBackBufferRelease is called again:
8) BackBufTex.Release(...); // Duplicate of 1
9) BackBufRTV.Release(...); // Duplicate of 2

OnBackBufferCreate is called again:
10) Device->CreateRenderTargetView (...); // Duplicate of 7

Maybe these duplicates mess things up ? Will try later when I get home.

**Comment by startas** [comment]
So i just tried newest code, and it seems that calling ResizeTarget() one more time did the trick, now new back buffer in fullscreen reports correct size.

**Comment by AustinBorger** [comment]
So the current commit works?

**Comment by startas** [comment]
Yes, at least for me it also works.

**Comment by AustinBorger** [comment]
Nice :)  Thanks for reporting the issue.
